#!/usr/bin/env node
/* ── Larum Property Experience™ — Offline pack builder ──────────────
   Reads properties/ + global configs and writes property-pack.js.

   The pack is a generated artefact. Never edit it by hand — edit the
   JSON under properties/ and run this again.

   Why it exists: opening index.html directly from disk (file://) blocks
   fetch(), so the demo needs the data inlined. Served over http:// the
   loader reads the JSON files and the pack is ignored.

   Usage: node build-pack.js
   ─────────────────────────────────────────────────────────────────── */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const PROPERTIES_DIR = path.join(ROOT, 'properties');
const OUT = path.join(ROOT, 'property-pack.js');

function readJSON(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function readJSONOr(file, fallback) {
  try { return readJSON(file); } catch { return fallback; }
}

function build() {
  const registry = readJSON(path.join(PROPERTIES_DIR, 'index.json'));
  const slugs = registry.order || [];
  if (!slugs.length) throw new Error('properties/index.json has an empty "order"');

  const pack = { registry, properties: {}, contact: null, purchase: null };

  for (const slug of slugs) {
    const dir = path.join(PROPERTIES_DIR, slug);
    if (!fs.existsSync(dir)) throw new Error(`properties/${slug}/ is listed in index.json but does not exist`);
    pack.properties[slug] = {
      content: readJSON(path.join(dir, 'content.json')),
      knowledge: readJSON(path.join(dir, 'knowledge.json')),
      assets: readJSONOr(path.join(dir, 'assets.json'), {})
    };
  }

  pack.contact = readJSONOr(path.join(ROOT, 'contact-config.json'), null);
  pack.purchase = readJSONOr(path.join(ROOT, 'purchase-config.json'), null);

  const banner = `/* GENERATED by build-pack.js — do not edit.\n` +
                 `   Source: properties/ + contact-config.json + purchase-config.json\n` +
                 `   Built: ${new Date().toISOString()}\n` +
                 `   Offline (file://) fallback only; http:// reads the JSON directly. */\n`;

  fs.writeFileSync(OUT, `${banner}window.LARUM_PACK = ${JSON.stringify(pack)};\n`, 'utf8');

  const kb = (fs.statSync(OUT).size / 1024).toFixed(1);
  console.log(`property-pack.js written — ${slugs.length} propert${slugs.length === 1 ? 'y' : 'ies'} (${slugs.join(', ')}), ${kb} KB`);

  /* The concierge function needs the same data server-side. A static ESM
     import is the only form Vercel's file tracing reliably bundles — reading
     JSON off the filesystem at runtime is not guaranteed to ship. */
  const apiDir = path.join(ROOT, 'api');
  fs.mkdirSync(apiDir, { recursive: true });
  /* Only what the concierge prompt actually reads. The intents,
     interestSignals and qualification blocks belong to the keyword engine,
     which runs in the browser — sending them to the model would just make
     the prompt larger, slower and dearer for no gain. */
  const slim = { properties: {} };
  for (const slug of slugs) {
    const { content, knowledge } = pack.properties[slug];
    slim.properties[slug] = {
      content: {
        label: content.label, brand: content.brand, title: content.title,
        subtitle: content.subtitle, intro: content.intro, shortRef: content.shortRef,
        facts: content.facts, sequences: content.sequences,
        dna: content.dna, setting: content.setting
      },
      knowledge: {
        property: knowledge.property,
        surroundings: knowledge.surroundings
      }
    };
  }

  const apiOut = path.join(apiDir, '_pack.mjs');
  fs.writeFileSync(apiOut, `${banner}export const PACK = ${JSON.stringify(slim)};\n`, 'utf8');
  const apiKb = (fs.statSync(apiOut).size / 1024).toFixed(1);
  console.log(`api/_pack.mjs written — concierge dossier only, ${apiKb} KB`);
}

try {
  build();
} catch (e) {
  console.error(`build-pack failed: ${e.message}`);
  process.exitCode = 1;
}
