/* ── Larum Property Experience™ — Property Loader ──────────────────
   Single source of truth per property. Replaces all embedded-*.js.

   Architecture:
   - Registry:  properties/index.json  → { default, order, rules }
   - Property:  properties/{slug}/content.json | knowledge.json | assets.json
   - Global:    contact-config.json, purchase-config.json
   - Loader merges everything and exposes it through accessors.

   Adding a property = drop a folder in properties/ and add its slug to
   properties/index.json. No code changes.

   Two runtime modes:
   - http(s):// → fetches the JSON files (authoring mode, no build step)
   - file://    → falls back to window.LARUM_PACK, generated by
                  `node build-pack.js` into property-pack.js
   ─────────────────────────────────────────────────────────────────── */

const LarumLoader = (() => {
  'use strict';

  const data = {
    properties: {},    // slug → { content, knowledge, assets }
    registry: null,    // { default, order, rules }
    contact: null,
    purchase: null,
    ready: false,
    source: null,      // 'files' | 'pack'
    errors: []
  };

  /* ── Auto-load: files first, offline pack as fallback ── */

  async function autoLoad(basePath) {
    basePath = basePath || '.';

    if (location.protocol !== 'file:') {
      try {
        const registry = await _fetchJSON(`${basePath}/properties/index.json`);
        const ok = await loadFromFiles(registry, basePath);
        if (ok) { data.source = 'files'; return true; }
        data.errors.push('File load incomplete — falling back to offline pack');
      } catch (e) {
        data.errors.push(`Registry unavailable (${e.message}) — falling back to offline pack`);
      }
    }

    if (window.LARUM_PACK) {
      _reset();
      const ok = loadFromPack(window.LARUM_PACK);
      if (ok) { data.source = 'pack'; return true; }
    } else {
      data.errors.push('No offline pack found. Run `node build-pack.js` or serve over http://');
    }

    data.ready = true;
    return false;
  }

  /* ── Load from separate JSON files ── */

  async function loadFromFiles(registry, basePath) {
    basePath = basePath || '.';
    data.registry = _normaliseRegistry(registry);

    const tasks = [];
    for (const slug of data.registry.order) {
      for (const part of ['content', 'knowledge', 'assets']) {
        tasks.push(
          _fetchJSON(`${basePath}/properties/${slug}/${part}.json`)
            .then(d => { _ensureProp(slug); data.properties[slug][part] = d; })
            .catch(e => data.errors.push(`${slug}/${part}: ${e.message}`))
        );
      }
    }

    tasks.push(
      _fetchJSON(`${basePath}/contact-config.json`)
        .then(d => { data.contact = d; })
        .catch(() => { data.contact = _defaultContact(); })
    );
    tasks.push(
      _fetchJSON(`${basePath}/purchase-config.json`)
        .then(d => { data.purchase = d; })
        .catch(() => { data.purchase = _defaultPurchase(); })
    );

    await Promise.allSettled(tasks);
    data.ready = true;
    return data.errors.length === 0;
  }

  /* ── Load from the generated offline pack ── */

  function loadFromPack(pack) {
    try {
      data.registry = _normaliseRegistry(pack.registry, Object.keys(pack.properties || {}));
      for (const [slug, prop] of Object.entries(pack.properties || {})) {
        data.properties[slug] = {
          content: prop.content || {},
          knowledge: prop.knowledge || {},
          assets: prop.assets || {}
        };
      }
      data.contact = pack.contact || _defaultContact();
      data.purchase = pack.purchase || _defaultPurchase();
      data.ready = true;
      return true;
    } catch (e) {
      data.errors.push(`Pack load error: ${e.message}`);
      return false;
    }
  }

  /* ── Accessors ── */

  function getPropertySlugs() {
    const order = data.registry?.order || [];
    const loaded = Object.keys(data.properties);
    /* Registry order wins; anything loaded but unlisted is appended. */
    return [
      ...order.filter(s => loaded.includes(s)),
      ...loaded.filter(s => !order.includes(s))
    ];
  }

  function getDefaultSlug() {
    const slugs = getPropertySlugs();
    const wanted = data.registry?.default;
    return slugs.includes(wanted) ? wanted : slugs[0] || null;
  }

  function getContent(slug)   { return data.properties[slug]?.content   || null; }
  function getKnowledge(slug) { return data.properties[slug]?.knowledge || null; }
  function getAssets(slug)    { return data.properties[slug]?.assets    || null; }
  function getContact()       { return data.contact; }
  function getPurchase()      { return data.purchase; }
  function getRules()         { return data.registry?.rules || {}; }
  function getSource()        { return data.source; }
  function isReady()          { return data.ready; }
  function getErrors()        { return data.errors.slice(); }

  function getPropertyLabel(slug) {
    return data.properties[slug]?.content?.label || slug;
  }

  /* Flat maps, keyed by slug — the shape the experience engine consumes. */
  function getContentMap()   { return _map('content'); }
  function getKnowledgeMap() { return _map('knowledge'); }
  function getAssetsMap()    { return _map('assets'); }

  /* ── Validation: what's missing for a property to be demo-ready ── */

  function validate(slug) {
    const prop = data.properties[slug];
    if (!prop) return { valid: false, issues: [`Property "${slug}" not found`], warnings: [] };

    const issues = [];    // blocks the demo
    const warnings = [];  // ships, but not final
    const c = prop.content || {};
    const k = prop.knowledge || {};
    const a = prop.assets || {};

    /* Content — identity */
    for (const f of ['label', 'brand', 'title', 'subtitle', 'intro', 'shortRef', 'conciergeIntro']) {
      if (!c[f]) issues.push(`content: missing ${f}`);
    }

    /* Content — narrative structure */
    if (!c.sequences || c.sequences.length < 3) issues.push('content: need at least 3 sequences (day moments)');
    if (!c.sceneSpaces || c.sceneSpaces.length !== (c.sequences || []).length) issues.push('content: sceneSpaces must have one entry per sequence');
    if (!c.spatial || c.spatial.length < 2) issues.push('content: need at least 2 spatial zones');
    if (!c.facts || c.facts.length < 3) issues.push('content: need at least 3 facts');
    if (!c.experiences || c.experiences.length < 3) issues.push('content: need at least 3 experiences');
    if (!c.dna?.dimensions?.length) issues.push('content: missing DNA dimensions');
    if (!c.setting?.cards?.length) issues.push('content: missing setting cards');

    /* Every DNA score must carry the line that justifies it, in both languages */
    for (const d of c.dna?.dimensions || []) {
      const label = Array.isArray(d) ? d[0] : d.label;
      if (Array.isArray(d)) { issues.push(`content: DNA "${label}" still uses the old array form — needs {label, score, note}`); continue; }
      if (!d.label || d.score == null) issues.push('content: a DNA dimension is missing label or score');
      for (const lg of ['en', 'es']) {
        if (!d.note?.[lg]) issues.push(`content: DNA "${label}" has no ${lg} note`);
      }
    }

    /* Every Setting card must point at a block the knowledge base can render */
    const surroundingKeys = Object.keys(k.surroundings || {});
    for (const card of c.setting?.cards || []) {
      const title = Array.isArray(card) ? card[0] : card.title;
      if (Array.isArray(card)) { issues.push(`content: setting card "${title}" still uses the old array form — needs {title, line, source}`); continue; }
      if (!card.title || !card.line) issues.push('content: a setting card is missing title or line');
      if (!card.source) { issues.push(`content: setting card "${title}" has no source`); continue; }
      if (card.source !== 'verification' && !surroundingKeys.includes(card.source)) {
        issues.push(`content: setting card "${title}" points at surroundings.${card.source}, which does not exist`);
      }
    }

    /* Content — spatial detail per zone */
    for (const lg of ['en', 'es']) {
      const nd = c.spatialNodeDetails?.[lg];
      if (!nd || nd.length !== (c.spatial || []).length) {
        issues.push(`content: spatialNodeDetails.${lg} must have one line per spatial zone`);
      }
    }

    /* Content — bilingual copy blocks */
    const copyKeys = ['identityNote', 'bandLabel', 'sequenceTitle', 'sequenceIntro', 'filmLabel',
                      'spatialTitle', 'spatialIntro', 'spatialDetail', 'detailsTitle', 'detailsIntro'];
    for (const key of copyKeys) {
      for (const lg of ['en', 'es']) {
        if (!c.copy?.[key]?.[lg]) issues.push(`content: missing copy.${key}.${lg}`);
      }
    }

    /* Content — arrival sequence */
    for (const lg of ['en', 'es']) {
      const ar = c.arrival?.[lg];
      if (!ar || ar.length !== 3) issues.push(`content: arrival.${lg} must have exactly 3 chapters`);
      else if (ar.some(s => s.length !== 3 || s.some(x => !x))) issues.push(`content: arrival.${lg} chapters need [eyebrow, title, text]`);
    }

    /* Content — calculator */
    if (!c.referencePrice) issues.push('content: missing referencePrice (calculator default)');
    if (!c.defaultRegion) issues.push('content: missing defaultRegion (calculator default)');
    else if (data.purchase && !data.purchase.regions?.[c.defaultRegion]) {
      warnings.push(`content: defaultRegion "${c.defaultRegion}" has no rates in purchase-config.json`);
    }

    /* Knowledge */
    if (!k.property?.facts) issues.push('knowledge: missing property facts');
    if (!k.intents || k.intents.length < 6) issues.push('knowledge: need at least 6 concierge intents');
    if (!k.surroundings) issues.push('knowledge: missing surroundings data');
    if (!k.interestSignals) issues.push('knowledge: missing interest signals');
    if (!k.qualification) issues.push('knowledge: missing qualification triggers');
    if (!k.fallback?.en || !k.fallback?.es) issues.push('knowledge: missing bilingual fallback response');

    /* Knowledge — every space referenced by the narrative must be described */
    const spaces = k.property?.spaces || {};
    if (Object.keys(spaces).length < 5) issues.push('knowledge: need at least 5 space descriptions');
    const referenced = new Set((c.sceneSpaces || []).flatMap(s => s[1] || []));
    for (const name of referenced) {
      if (!spaces[name]) issues.push(`knowledge: space "${name}" is used in sceneSpaces but has no description`);
      else if (!spaces[name].descriptionEs) warnings.push(`knowledge: space "${name}" has no Spanish description`);
    }

    /* Assets */
    const heroImage = a.hero?.fallbackImage || c.image;
    if (!heroImage) issues.push('assets: no hero image');
    if (!a.bandImage && !c.band) issues.push('assets: no band image');
    if (/placeholder/.test(heroImage || '')) warnings.push('assets: hero is still a generated placeholder');
    else if (a.authorised !== true) warnings.push('assets: stand-in photography — not yet authorised by the agency');
    if (!a.propertyFilm) warnings.push('assets: no property film');

    /* Stand-ins must say where they came from, so nothing untraceable ships */
    if (a.authorised !== true) {
      if (a.hero?.fallbackImage && !a.hero.provenance) warnings.push('assets: hero has no provenance recorded');
      if (a.bandImage && !a.bandProvenance) warnings.push('assets: band image has no provenance recorded');
    }

    /* Facts confirmation status */
    const facts = k.property?.facts || {};
    const unconfirmed = Object.entries(facts).filter(([, v]) => v.status !== 'confirmed');
    if (unconfirmed.length) {
      warnings.push(`knowledge: ${unconfirmed.length} fact(s) not confirmed by the agency (${unconfirmed.map(([n]) => n).join(', ')})`);
    }

    return {
      valid: issues.length === 0,
      issues,
      warnings,
      summary: {
        slug,
        label: c.label || slug,
        sequences: c.sequences?.length || 0,
        spaces: Object.keys(spaces).length,
        intents: k.intents?.length || 0,
        confirmedFacts: Object.values(facts).filter(f => f.status === 'confirmed').length,
        totalFacts: Object.keys(facts).length,
        assetState: /placeholder/.test(heroImage || '') ? 'placeholder'
                  : a.authorised === true ? 'authorised' : 'stand-in',
        spaceImages: Object.keys(a.spaces || {}).length
      }
    };
  }

  function validateAll() {
    const results = {};
    for (const slug of getPropertySlugs()) results[slug] = validate(slug);
    return results;
  }

  /* ── Export the offline pack shape (used by build-pack.js) ── */

  function exportPack() {
    const pack = { registry: data.registry, properties: {}, contact: data.contact, purchase: data.purchase };
    for (const [slug, prop] of Object.entries(data.properties)) {
      pack.properties[slug] = { content: prop.content, knowledge: prop.knowledge, assets: prop.assets };
    }
    return pack;
  }

  /* ── Internals ── */

  function _map(part) {
    const out = {};
    for (const slug of getPropertySlugs()) out[slug] = data.properties[slug][part];
    return out;
  }

  function _normaliseRegistry(registry, fallbackOrder) {
    const r = registry || {};
    const order = Array.isArray(r.order) && r.order.length ? r.order : (fallbackOrder || []);
    return { default: r.default || order[0] || null, order, rules: r.rules || {} };
  }

  function _ensureProp(slug) {
    if (!data.properties[slug]) data.properties[slug] = { content: {}, knowledge: {}, assets: {} };
  }

  function _reset() {
    data.properties = {};
    data.registry = null;
    data.contact = null;
    data.purchase = null;
    data.ready = false;
  }

  async function _fetchJSON(url) {
    const r = await fetch(url, { cache: 'no-cache' });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  }

  function _defaultContact() {
    return { defaultEmail: 'contacto@larumstudio.com', properties: {}, mode: 'mailto', endpoint: null };
  }

  function _defaultPurchase() {
    return {
      defaults: {
        resale: { notary: 0.5, registry: 0.3, legal: 1.0, agency: 0, other: 0 },
        new: { vat: 10, ajd: 1.5, notary: 0.5, registry: 0.3, legal: 1.0, agency: 0, other: 0 }
      },
      regions: {}
    };
  }

  return {
    autoLoad, loadFromFiles, loadFromPack,
    getPropertySlugs, getDefaultSlug, getContent, getKnowledge, getAssets,
    getContentMap, getKnowledgeMap, getAssetsMap,
    getContact, getPurchase, getPropertyLabel, getRules, getSource,
    isReady, getErrors, validate, validateAll, exportPack
  };
})();

if (typeof window !== 'undefined') window.LarumLoader = LarumLoader;
if (typeof module !== 'undefined' && module.exports) module.exports = LarumLoader;
