#!/usr/bin/env node
/* ── Larum — seed generator ─────────────────────────────────────────
   Turns properties/ into docs/migrations/002_seed_properties.sql.

   Why generate SQL instead of writing to Supabase directly: seeding the
   canonical table needs write access to `properties`, and the only key
   this project holds is the anon key — which must never be able to write
   there. Emitting SQL keeps the privileged step where it belongs, in the
   operator's own SQL editor, and makes the migration reviewable before it
   runs rather than after.

   The output is idempotent (ON CONFLICT DO UPDATE), so re-running it
   after editing a JSON file re-syncs that property.

   Usage: node tools/generate-seed.js
   ─────────────────────────────────────────────────────────────────── */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const PROPERTIES = path.join(ROOT, 'properties');
const OUT = path.join(ROOT, 'docs', 'migrations', '002_seed_properties.sql');

const ORG = { name: 'Larum Studio', slug: 'larum-studio', email: 'contactolarum@gmail.com' };

/* Dollar-quoting rather than doubling quotes: the dossiers are 25 KB of
   prose full of apostrophes ("Christie's", "l'entrée"), and one missed
   escape would corrupt a knowledge base silently. */
const TAG = '$larum$';
function q(value) {
  const json = JSON.stringify(value);
  if (json.includes(TAG)) throw new Error('JSON contains the dollar-quote tag — choose another');
  return `${TAG}${json}${TAG}::jsonb`;
}
function s(value) {
  if (value === null || value === undefined) return 'NULL';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function readJSON(...p) {
  return JSON.parse(fs.readFileSync(path.join(...p), 'utf8'));
}

/* "Christie's" → christie-s. Accents stripped so Andalucía-style names
   survive the slug constraint in the schema. */
function agencySlug(name) {
  return String(name || '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function build() {
  const registry = readJSON(PROPERTIES, 'index.json');
  const slugs = registry.order || [];
  if (!slugs.length) throw new Error('properties/index.json has an empty "order"');

  const props = slugs.map(slug => ({
    slug,
    content: readJSON(PROPERTIES, slug, 'content.json'),
    knowledge: readJSON(PROPERTIES, slug, 'knowledge.json'),
    assets: readJSON(PROPERTIES, slug, 'assets.json')
  }));

  /* One agent per agency, named after the brand. These are placeholders
     standing in for the real advisor at each firm — the admin renames
     them once we know who they are. The relationship is what matters now. */
  const agencies = [...new Set(props.map(p => p.content.brand).filter(Boolean))];

  const out = [];
  const w = line => out.push(line);

  w('-- ═══════════════════════════════════════════════════════════════════════');
  w('-- LARUM — PHASE 1 · MILESTONE 2 · SEED');
  w('--');
  w('-- GENERATED by tools/generate-seed.js — do not edit by hand.');
  w(`-- Source: properties/ · Built: ${new Date().toISOString()}`);
  w('--');
  w('-- Run AFTER 001_phase1_schema.sql. Idempotent: re-running re-syncs');
  w('-- each property from its JSON files.');
  w('--');
  w('-- After this runs, the database is the canonical source and the JSON');
  w('-- files become the offline seed/export path.');
  w('-- ═══════════════════════════════════════════════════════════════════════');
  w('');
  w('BEGIN;');
  w('');

  w('-- 1 · Organization');
  w(`INSERT INTO public.organizations (name, slug, contact_email, status)`);
  w(`VALUES (${s(ORG.name)}, ${s(ORG.slug)}, ${s(ORG.email)}, 'active')`);
  w(`ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, contact_email = EXCLUDED.contact_email;`);
  w('');

  w('-- 2 · Agents (placeholders named after the agency, renamed later in Admin)');
  for (const agency of agencies) {
    const slug = agencySlug(agency);
    w(`INSERT INTO public.agents (organization_id, name, slug, agency, role, status)`);
    w(`SELECT o.id, ${s(agency)}, ${s(slug)}, ${s(agency)}, 'Property advisor', 'active'`);
    w(`FROM public.organizations o WHERE o.slug = ${s(ORG.slug)}`);
    w(`ON CONFLICT (slug) DO UPDATE SET agency = EXCLUDED.agency, name = EXCLUDED.name;`);
    w('');
  }

  w('-- 3 · Properties');
  props.forEach((p, i) => {
    const agent = agencySlug(p.content.brand);
    const isDefault = registry.default === p.slug;

    w(`-- ${p.slug} — ${p.content.label || ''}`);
    w(`INSERT INTO public.properties (`);
    w(`  organization_id, agent_id, slug, status, content, knowledge, assets,`);
    w(`  display_order, is_default, published_at`);
    w(`)`);
    w(`SELECT`);
    w(`  o.id,`);
    w(`  (SELECT a.id FROM public.agents a WHERE a.slug = ${s(agent)}),`);
    w(`  ${s(p.slug)},`);
    /* Both are live on the production URL today; anything else would take
       them offline the moment the experience starts reading the database. */
    w(`  'published',`);
    w(`  ${q(p.content)},`);
    w(`  ${q(p.knowledge)},`);
    w(`  ${q(p.assets)},`);
    w(`  ${i},`);
    w(`  ${isDefault},`);
    w(`  now()`);
    w(`FROM public.organizations o WHERE o.slug = ${s(ORG.slug)}`);
    w(`ON CONFLICT (slug) DO UPDATE SET`);
    w(`  content = EXCLUDED.content,`);
    w(`  knowledge = EXCLUDED.knowledge,`);
    w(`  assets = EXCLUDED.assets,`);
    w(`  agent_id = EXCLUDED.agent_id,`);
    w(`  display_order = EXCLUDED.display_order,`);
    w(`  is_default = EXCLUDED.is_default;`);
    w('');
  });

  w('-- 4 · Backfill the existing analytics from the text slug.');
  w('--     The text column stays; this only fills the new foreign key.');
  for (const table of ['leads', 'sessions', 'analytics_events']) {
    w(`UPDATE public.${table} t SET property_id = p.id`);
    w(`FROM public.properties p WHERE p.slug = t.property AND t.property_id IS NULL;`);
  }
  w('');

  w('COMMIT;');
  w('');
  w('-- ── Verify ──────────────────────────────────────────────────────────');
  w('SELECT slug, status, name_en, location, price, reference, is_default');
  w('FROM public.properties ORDER BY display_order;');
  w('');
  w('-- Rows still not linked to a property (expect only probe/legacy slugs):');
  w("SELECT 'leads' AS t, property, count(*) FROM public.leads WHERE property_id IS NULL GROUP BY property");
  w("UNION ALL SELECT 'sessions', property, count(*) FROM public.sessions WHERE property_id IS NULL GROUP BY property");
  w("UNION ALL SELECT 'events', property, count(*) FROM public.analytics_events WHERE property_id IS NULL GROUP BY property;");
  w('');

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, out.join('\n'), 'utf8');

  const kb = (fs.statSync(OUT).size / 1024).toFixed(1);
  console.log(`002_seed_properties.sql written — ${props.length} propert${props.length === 1 ? 'y' : 'ies'} (${slugs.join(', ')}), ${agencies.length} agent(s), ${kb} KB`);
}

try {
  build();
} catch (e) {
  console.error(`generate-seed failed: ${e.message}`);
  process.exitCode = 1;
}
